### ISSUE TITLE
Advanced UI doesnt work

### ISSUE THREAD

**Issue by patpac9** [DeebotUniverse/docs#119]
Hello :)

Nice work by the way! I lOVE "Deebot 4 Home Assistant"

Unfortunately the room selection does not work.
https://deebot.readthedocs.io/integrations/home-assistant/examples/ui/advanced/

I copied everything and just replaced "Susi" with the name of my vacuum cleaner. No matter what I do, he always writes the value "2" in the UI queue and deselects the previously selected.

___________________________________________________________________________________________________

**Here is the Template out of configurations yaml:**
```yaml
template:
  unique_id: deebot_saugstauberos_queue # change me
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: variable.deebot_saugstauberos_queue # change me
  sensor:
    # Add for each room the following. Change room_name accordingly
    - unique_id: deebot_saugstauberos_queue_living_room # change me
      name: deebot_saugstauberos_queue_living_room # change me
      # room_name must match the room name provided by the vacuum
      state: >
        {% set room_name = "living_room" %}
        {% set queue = trigger.to_state.state.split(",") if trigger.to_state is defined else "" %}
        {{ queue.index(room_name)+1 if room_name in queue else 0 }}
    - unique_id: deebot_saugstauberos_queue_kitchen # change me
      name: deebot_saugstauberos_queue_kitchen # change me
      # room_name must match the room name provided by the vacuum
      state: >
        {% set room_name = "kitchen" %}
        {% set queue = trigger.to_state.state.split(",") if trigger.to_state is defined else "" %}
        {{ queue.index(room_name)+1 if room_name in queue else 0 }}
    - unique_id: deebot_saugstauberos_queue_corridor # change me
      name: deebot_saugstauberos_queue_corridor # change me
      # room_name must match the room name provided by the vacuum
      state: >
        {% set room_name = "corridor" %}
        {% set queue = trigger.to_state.state.split(",") if trigger.to_state is defined else "" %}
        {{ queue.index(room_name)+1 if room_name in queue else 0 }}
```
___________________________________________________________________________________________________

**and here is my UI yaml:**
```yaml
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        template: vacuum_room
        entity: sensor.deebot_saugstauberos_queue_living_room
        icon: mdi:sofa
        name: Wohnzimmer
        tap_action:
          service_data:
            room: living_room
      - type: custom:button-card
        template: vacuum_room
        entity: sensor.deebot_saugstauberos_queue_kitchen
        icon: mdi:silverware-variant
        name: Küche
        tap_action:
          service_data:
            room: kitchen
      - type: custom:button-card
        template: vacuum_room
        entity: sensor.deebot_saugstauberos_queue_corridor
        icon: mdi:shoe-print
        name: Gang
        tap_action:
          service_data:
            room: corridor
```
___________________________________________________________________________________________________

Here some info about my env:
HASS 2022.4.1.
hass-variables 2.2.1
Button Card 3.4.2
