### ISSUE TITLE
Deebot T10 map support

### ISSUE THREAD

**Issue by TruantRiccardo** [DeebotUniverse/docs#247]
Hi, I have the Deebot T10 plus and it works perfectly except for the map.
![image](https://github.com/DeebotUniverse/docs/assets/44238224/34f3021d-90e6-448d-bb8f-ebce540c9af9)

As you can see, even after the 2.0 update, the map is not loaded correctly.
How can I help improve support for this model?

**Comment by rahulpdev** [comment]
> Hi, I have the Deebot T10 plus and it works perfectly except for the map. ![image](https://user-images.githubusercontent.com/44238224/258214243-34f3021d-90e6-448d-bb8f-ebce540c9af9.png)
> 
> As you can see, even after the 2.0 update, the map is not loaded correctly. How can I help improve support for this model?

I also have the T10 Plus, are you able to clean zones in your house via Home Assistant? I haven't figured out how to do that!

**Comment by TruantRiccardo** [comment]
Hi @rahulpdev , yes.
If you access the attributes of your vacuum entity you will see a number associated with the zones in your home.
From this, you can use the service vacuum.send_command to execute the command spot_area by providing as params the number (or the list of numbers) associated with the zones you want to clean. e.g.:

```
  service: vacuum.send_command
  target:
    entity_id: //your vacuum entity
  data:
    command: spot_area
    params:
      rooms: 4, 3
      cleanings: 1
```
