### ISSUE TITLE
Selected rooms buttons do not change in color

### ISSUE THREAD

**Issue by WiDri** [DeebotUniverse/docs#253]
Selecting rooms does not change colors of the button. So i can't see the selected rooms before starting the cleaning.

Could someone point me in the right direction where the problem could be? 
Clicking the room does enable the start button. Clicking again enables the lock. 

![image](https://github.com/DeebotUniverse/docs/assets/60379402/109f00c7-2c35-4ff6-84c6-07320f1003fa)

Best regards,
Wietse

**Comment by edenhaus** [comment]
You need to add the required things of the advanced example. In the left upper corner, you see ù..`, and if you open the entity in developer tools, you will see that it has the state undefined. This means you haven't set it up correctly. Please recheck your config and compare it with the example you probably missed something.

**Comment by WiDri** [comment]
I found it, had a wrong indentation. 

Thanks!

**Comment by juanpa669** [comment]
Hello there,

@WiDri Can you tell me where do you have had bad indentation, I got **_'u..'_** in the room card and do not find where is the problem.

Thanks

Thanks to authors for this amazing integration !

**Comment by WiDri** [comment]
@juanpa669 
It's a while ago so i don't remember the exact details. I have 2 parts in my raw dashboard config.
U must also make sure both are properly indented in the config editor otherwise u receive errors, this was the tricky part for me. this works for me without errors not sure if it's entirely correct.
**This starts at line 1 so it's before al the other dashboard config that's already there.** 

```
button_card_templates:
  vacuum_service:
    color: var(--text-color)
    entity: vacuum.baddy
    tap_action:
      action: call-service
      service_data:
        entity_id: vacuum.baddy
    lock:
      enabled: |
        [[[ return variables.enabled ]]]
      exemptions: []
    styles:
      card:
        - height: 80px
      lock:
        - color: var(--primary-text-color)
    state:
      - operator: template
        value: |
          [[[ return variables.enabled ]]]
        styles:
          card:
            - color: var(--disabled-text-color)
  vacuum_room:
    color: var(--text-color)
    variables:
      lock_enabled: >
        [[[ return ['cleaning', 'paused'].includes(states['vacuum.baddy'].state)
        ]]]
    state:
      - operator: template
        value: |
          [[[ return variables.lock_enabled && entity.state == 0 ]]]
        styles:
          card:
            - color: var(--disabled-text-color)
      - styles:
          card:
            - background-color: var(--primary-color)
        operator: '>='
        value: 1
    styles:
      card:
        - font-size: 12px
      grid:
        - position: relative
      custom_fields:
        order:
          - display: |
              [[[
                if (entity.state == "0")
                  return "none";
                return "block";
              ]]]
          - position: absolute
          - left: 5%
          - top: 5%
          - height: 20px
          - width: 20px
          - font-size: 20px
          - font-weight: bold
          - line-height: 20px
    custom_fields:
      order: |
        [[[ return entity.state ]]]
    tap_action:
      action: call-service
      service: script.deebot_room_queue
      service_data:
        queue: input_text.deebot_baddy_queue
    lock:
      enabled: |
        [[[ return variables.lock_enabled ]]]
      exemptions: []
```


**then there's the part for the actual dashboard tab in the raw config, which is further down in the config**

```
- title: Schoonmaken
    path: schoonmaken
    subview: false
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: custom:vacuum-card
            entity: vacuum.baddy
            stats:
              default:
                - entity_id: sensor.baddy_brush
                  unit: '%'
                  subtitle: Hauptbürste
                - entity_id: sensor.baddy_side_brush
                  unit: '%'
                  subtitle: Seitenbürsten
                - entity_id: sensor.baddy_filter
                  unit: '%'
                  subtitle: Filter
              cleaning:
                - entity_id: sensor.baddy_stats_area
                  unit: m²
                  subtitle: Geputzte Fläche
                - entity_id: sensor.baddy_stats_time
                  unit: Minuten
                  subtitle: Reinigungsdauer
            show_status: true
            show_toolbar: false
            compact_view: true
          - type: custom:button-card
            color: auto-no-temperature
            name: Räume zum Putzen auswählen
            styles:
              card:
                - font-size: 18px
                - height: 30px
              name:
                - color: var(--primary-color)
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                template: vacuum_room
                entity: sensor.deebot_baddy_queue_kitchen
                icon: mdi:silverware-fork-knife
                name: Keuken
                tap_action:
                  service_data:
                    room: kitchen
              - type: custom:button-card
                template: vacuum_room
                entity: sensor.deebot_baddy_queue_corridor
                icon: mdi:hanger
                name: Hal
                tap_action:
                  service_data:
                    room: corridor
              - type: custom:button-card
                template: vacuum_room
                entity: sensor.deebot_baddy_queue_kids_room
                icon: mdi:desk
                name: Bureau
                tap_action:
                  service_data:
                    room: kids_room
              - type: custom:button-card
                template: vacuum_room
                entity: sensor.deebot_baddy_queue_living_room
                icon: mdi:sofa
                name: Woonkamer
                tap_action:
                  service_data:
                    room: living_room
          - type: horizontal-stack
            cards:
              - type: conditional
                conditions:
                  - entity: vacuum.baddy
                    state_not: cleaning
                  - entity: vacuum.baddy
                    state_not: paused
                card:
                  type: custom:button-card
                  template: vacuum_service
                  icon: mdi:play
                  name: Start
                  tap_action:
                    action: call-service
                    service: script.deebot_clean
                  variables:
                    enabled: |
                      [[[ 
                        return ((!states['input_text.deebot_baddy_queue'].state || 
                            states['input_text.deebot_baddy_queue'].state.length === 0)
                            && ['docked', 'idle', 'error', 'returning'].includes(entity.state))
                      ]]]
              - type: conditional
                conditions:
                  - entity: vacuum.baddy
                    state: cleaning
                card:
                  type: custom:button-card
                  color: auto
                  icon: mdi:pause
                  name: Pause
                  tap_action:
                    action: call-service
                    service: vacuum.pause
                    service_data:
                      entity_id: vacuum.baddy
                  styles:
                    card:
                      - height: 80px
                      - background-color: var(-color)
              - type: conditional
                conditions:
                  - entity: vacuum.baddy
                    state: paused
                card:
                  type: custom:button-card
                  color: auto
                  icon: mdi:play-pause
                  name: Weiter
                  tap_action:
                    action: call-service
                    service: vacuum.start
                    service_data:
                      entity_id: vacuum.baddy
                  styles:
                    card:
                      - height: 80px
                      - background-color: var(-color)
              - type: custom:button-card
                template: vacuum_service
                icon: mdi:stop
                name: Stop
                tap_action:
                  service: vacuum.stop
                variables:
                  enabled: |
                    [[[ 
                      return !(['cleaning', 'paused', 'returning'].includes(entity.state))
                    ]]]
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                template: vacuum_service
                icon: mdi:home-map-marker
                name: Zurück zur Ladestation
                tap_action:
                  service: vacuum.return_to_base
                variables:
                  enabled: |
                    [[[ 
                      return ['docked', 'returning'].includes(entity.state)
                    ]]]
              - type: custom:button-card
                color: auto
                icon: mdi:map-marker
                name: Lokalisieren
                tap_action:
                  action: call-service
                  service: vacuum.locate
                  service_data:
                    entity_id: vacuum.baddy
                styles:
                  card:
                    - height: 80px
                    - background-color: var(-color)
          - type: picture-entity
            entity: image.baddy_map
            tap_action:
              action: none
            hold_action:
              action: none
            show_state: false
            show_name: false
```

Maybe it gives you an idea of might be wrong, there could be other problems in the other things you need to config.
