### ISSUE TITLE
Cleaning a custom area by name, not by coordinates?

### ISSUE THREAD

**Issue by redlefloh** [DeebotUniverse/docs#263]
Hi all, I really enjoy the integration, thanks so much! I have a question, can I clean a custom area and reuse the custom areas defined in the Ecovacs App, e.g. "Pet Area Cleaning" instead of defining coordinates as described in [custom_area command](https://deebot.readthedocs.io/integrations/home-assistant/examples/commands/). 

It would be really great if one could just specify the names given in the App since it is easy to define the custom areas there. Is there a way?  I imagine something like:
```
service: vacuum.send_command
target:
  entity_id: vacuum.YOUR_ROBOT_NAME
data:
  command: custom_area
  params:
    name: 'Pet Cleaning Area'
```

Also, is there also a way to add cleaning preferences to this command?

Thanks!
